### ISSUE TITLE
error while testing video

### ISSUE THREAD

**Issue by vihari1729** [hritik7080/Car-License-Plate-Recognition#1]
Hi,
I cloned your repository and tested with your video and got the following error

`ValueError: not enough values to unpack (expected 3, got 2)`

not sure, what went wrong. could you please help me in testing the video

**Comment by hritik7080** [comment]
Hi @vihari1729,
The problem is with the version of your OpenCV.
I have just included my article in the repository, make sure you install all the libraries with given versions.

**Comment by vihari1729** [comment]
Yes, it is working if i change the opencv version and try with your video. but not working on any of my videos.

**Comment by hritik7080** [comment]
There may be the problem of camera angle or the size of the plate coming in the frame. 
If you see in the constructor of Plate Finder Class, I have set min and max area values for the plate contour. If the program not extracting the plate from your video that means the area of the plate contour doesn't lie within the given range.

**Comment by vihari1729** [comment]
The indian plate is of 10 characterstics. it is only detecting 8 or 9 characters in live and after getting detected, the characters recognition it is giving few false values. maybe u didn't train with all alphabets and digits

**Comment by hritik7080** [comment]
Yeah @vihari1729 
Actually I didn't found any suitable Indian video for testing and this is an implementation of a research paper, so I have done everything with respect to that given video.
Maybe you should refer to the article. I have written all the limitations of this CV model there.
![Screenshot (316)](https://user-images.githubusercontent.com/41755284/92474803-0e2a6980-f1fa-11ea-855c-be3576dc7132.png)
