### ISSUE TITLE
Add New Characters

### ISSUE THREAD

**Issue by absurdprofit** [hritik7080/Car-License-Plate-Recognition#2]
How would I go about adding new letters to the AI?

**Comment by hritik7080** [comment]
> How would I go about adding new letters to the AI?

You can train another digit recognition model with tensorflow and replace the .pb and label files with yours.🙂

**Comment by absurdprofit** [comment]
> > How would I go about adding new letters to the AI?
> 
> You can train another digit recognition model with tensorflow and replace the .pb and label files with yours.🙂

Ok thanks
